# theme
import = [
    # "~/dotfiles/alacritty_themes/themes/monokai_charcoal.toml"
    # "~/dotfiles/alacritty_themes/themes/iceberg.toml"
    "~/dotfiles/alacritty_themes/themes/ayu_dark.toml"
    # "~/dotfiles/alacritty_themes/themes/tomorrow_night_bright.toml"
    # "~/dotfiles/alacritty_themes/themes/terminal_app.toml"
]


[env]
TERM = "xterm-256color"

[window]

padding.x = 10
padding.y = 10
decorations = "Buttonless"

[font]
normal = { family = "PragmataPro for Powerline", style = "Regular" }
bold = { style = "Regular" }
italic = { style = "Italic" }
bold_italic = { style = "Italic" }
offset = { x = 0, y = 4 }
size = 15

[cursor]
style = { shape = "Block", blinking = "Off" }
blink_interval = 300

[mouse]
hide_when_typing = true

[colors.primary]
background = "#000000"



